name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up uv
        uses: astral-sh/setup-uv@v4

      - name: Sync dependencies with uv (locked)
        run: |
          uv sync --frozen
          uv pip install pytest
      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}/multi_doc_chat
          GROQ_API_KEY: dummy
          GOOGLE_API_KEY: dummy
          LLM_PROVIDER: google
        run: |
          uv run pytest -q